# Generated by Django 5.1.5 on 2025-05-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tenant_alter_businessunits_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_country',
            field=models.ForeignKey(blank=True, db_column='company_country', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_location',
            field=models.ForeignKey(blank=True, db_column='company_location', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locations'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='country_code',
            field=models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='business_unit',
            field=models.ForeignKey(blank=True, db_column='business_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_business_unit', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_category', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='company_code',
            field=models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_company_code', to='api.companies'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cost_center_code',
            field=models.ForeignKey(blank=True, db_column='cost_center_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_cost_center_code', to='api.costcenters'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cost_center_name',
            field=models.ForeignKey(blank=True, db_column='cost_center_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_cost_center_name', to='api.costcenters'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.countries'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='function',
            field=models.ForeignKey(blank=True, db_column='function', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_function', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='grade_level',
            field=models.ForeignKey(blank=True, db_column='grade_level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_grade_level', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='health_insurance_code',
            field=models.ForeignKey(blank=True, db_column='health_insurance_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_health_insurance_code', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='health_insurance_name',
            field=models.ForeignKey(blank=True, db_column='health_insurance_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_health_insurance_name', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='health_insurance_plan',
            field=models.ForeignKey(blank=True, db_column='health_insurance_plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_health_insurance_plan', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='internal_order_code',
            field=models.ForeignKey(blank=True, db_column='internal_order_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_internal_order_code', to='api.internalorders'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='internal_order_name',
            field=models.ForeignKey(blank=True, db_column='internal_order_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_internal_order_name', to='api.internalorders'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_code',
            field=models.ForeignKey(blank=True, db_column='job_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_job_code', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_family_group',
            field=models.ForeignKey(blank=True, db_column='job_family_group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_job_family_group', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_family_name',
            field=models.ForeignKey(blank=True, db_column='job_family_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_job_family_name', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_position_name',
            field=models.ForeignKey(blank=True, db_column='job_position_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_job_position_name', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_profile',
            field=models.ForeignKey(blank=True, db_column='job_profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_job_profile', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='location_code',
            field=models.ForeignKey(blank=True, db_column='location_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_location_code', to='api.locations'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='location_name',
            field=models.ForeignKey(blank=True, db_column='location_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_location_name', to='api.locations'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='management_level_1',
            field=models.ForeignKey(blank=True, db_column='management_level_1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_at_management_level_1', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='management_level_2',
            field=models.ForeignKey(blank=True, db_column='management_level_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_at_management_level_2', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='manager_first_name',
            field=models.ForeignKey(blank=True, db_column='manager_first_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed_by_first_name', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='manager_full_legal_name',
            field=models.ForeignKey(blank=True, db_column='manager_full_legal_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed_by_full_name', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='manager_id',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='manager_last_name',
            field=models.ForeignKey(blank=True, db_column='manager_last_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_managed_by_last_name', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pay_group_name',
            field=models.ForeignKey(blank=True, db_column='pay_group_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_pay_group_name', to='api.paygroups'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statesorprovinces'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='scheduled_weekly_hours',
            field=models.ForeignKey(blank=True, db_column='scheduled_weekly_hours', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workscheduled'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='sub_function',
            field=models.ForeignKey(blank=True, db_column='sub_function', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_sub_function', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='union_name',
            field=models.ForeignKey(blank=True, db_column='union_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_by_union_name', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='business_unit',
            field=models.ForeignKey(blank=True, db_column='business_unit', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='company_code',
            field=models.ForeignKey(blank=True, db_column='company_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.companies'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='cost_center_code',
            field=models.ForeignKey(blank=True, db_column='cost_center_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.costcenters'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='cost_center_name',
            field=models.ForeignKey(blank=True, db_column='cost_center_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.costcenters'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.countries'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='function',
            field=models.ForeignKey(blank=True, db_column='function', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='grade_level',
            field=models.ForeignKey(blank=True, db_column='grade_level', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='health_insurance_code',
            field=models.ForeignKey(blank=True, db_column='health_insurance_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='health_insurance_name',
            field=models.ForeignKey(blank=True, db_column='health_insurance_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='health_insurance_plan',
            field=models.ForeignKey(blank=True, db_column='health_insurance_plan', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.healthinsurances'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='internal_order_code',
            field=models.ForeignKey(blank=True, db_column='internal_order_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.internalorders'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='internal_order_name',
            field=models.ForeignKey(blank=True, db_column='internal_order_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.internalorders'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='job_code',
            field=models.ForeignKey(blank=True, db_column='job_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='job_family_group',
            field=models.ForeignKey(blank=True, db_column='job_family_group', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='job_family_name',
            field=models.ForeignKey(blank=True, db_column='job_family_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='job_position_name',
            field=models.ForeignKey(blank=True, db_column='job_position_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='job_profile',
            field=models.ForeignKey(blank=True, db_column='job_profile', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobpositions'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='location_code',
            field=models.ForeignKey(blank=True, db_column='location_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.locations'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='location_name',
            field=models.ForeignKey(blank=True, db_column='location_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.locations'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='management_level_1',
            field=models.ForeignKey(blank=True, db_column='management_level_1', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='management_level_2',
            field=models.ForeignKey(blank=True, db_column='management_level_2', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='manager_first_name',
            field=models.ForeignKey(blank=True, db_column='manager_first_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='manager_full_legal_name',
            field=models.ForeignKey(blank=True, db_column='manager_full_legal_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='manager_id',
            field=models.ForeignKey(blank=True, db_column='manager_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='manager_last_name',
            field=models.ForeignKey(blank=True, db_column='manager_last_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='pay_group_name',
            field=models.ForeignKey(blank=True, db_column='pay_group_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.paygroups'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.statesorprovinces'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='scheduled_weekly_hours',
            field=models.ForeignKey(blank=True, db_column='scheduled_weekly_hours', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.workscheduled'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='sub_function',
            field=models.ForeignKey(blank=True, db_column='sub_function', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.businessunits'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='union_name',
            field=models.ForeignKey(blank=True, db_column='union_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.unionsubgroups'),
        ),
        migrations.AlterField(
            model_name='jobpositions',
            name='job_family_name',
            field=models.ForeignKey(blank=True, db_column='job_family_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobfamilies'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country_code',
            field=models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='region_code',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statesorprovinces'),
        ),
        migrations.AlterField(
            model_name='statesorprovinces',
            name='country_code',
            field=models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
    ]
