# Generated by Django 5.1.5 on 2025-05-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_unionsubgroups_union_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.currencies'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.currencies'),
        ),
    ]
