services:
  - type: web
    name: orvyn-backend
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
