# Generated by Django 5.1.5 on 2025-05-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_companies_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unionsubgroups',
            name='union_code',
            field=models.ForeignKey(blank=True, db_column='union_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unions'),
        ),
    ]
